table ip xray {
	chain dns_redirect {
		type nat hook prerouting priority filter - 10; policy accept;
		udp dport 53 redirect to :15353
		tcp dport 53 redirect to :15353
	}

	chain prerouting {
		type nat hook prerouting priority dstnat; policy accept;
		ip daddr 0.0.0.0/8 return
		ip daddr 10.0.0.0/8 return
		ip daddr 127.0.0.0/8 return
		ip daddr 169.254.0.0/16 return
		ip daddr 172.16.0.0/12 return
		ip daddr 192.168.0.0/16 return
		ip daddr 224.0.0.0/4 return
		ip daddr 240.0.0.0/4 return
		ip daddr 78.40.196.176 return
		tcp dport != 22 redirect to :12345
	}
}
